In [60]:
import pandas as pd

In [61]:
data = {
    'Name':['Sumon','Rana','Akij','Samsung','opppo'],
    'City':['Satkhira','khulna','Motijhil Moddhopara Dhaka','Dhaka Motijhil','khulnb'],
    'Department': ['Hr','President','Company','hel','hek'],
    'Saalry':[1000,100,24444,20,200]
}
df = pd.DataFrame(data)

In [62]:
# city that start with motijhi
df.loc[df['City'].str.contains(r'^Motijhil')]

   Name                       City Department  Saalry
2  Akij  Motijhil Moddhopara Dhaka    Company   24444

In [64]:
# city that end with na

df.loc[df['City'].str.contains(r'na$')]

   Name    City Department  Saalry
1  Rana  khulna  President     100